### DISCUSSION TITLE
How can I get the /boot artifacts from a bootc container image?

### DISCUSSION THREAD

**Discussion by mangelajo** [bootc-dev/bootc#493] [Q&A] [answered]
I have been looking at measuring the boot binaries from a bootc container image, in order to pre-calculate TPM PCR9 expected values, may be even PCR8 (but that one is tricker because of variable expansion in grub..).

i.e. if We look at the binary bios measurement log we find that the following files were measured by grub:
```
# tpm2_eventlog /sys/kernel/security/tpm0/binary_bios_measurements | grep "PCRIndex: 9" -A10 | grep String -A 1
    String: |-
      "(hd0,gpt2)/EFI/centos/grub.cfg\0"
--
    String: |-
      "(hd0,gpt2)/EFI/centos/grub.cfg\0"
--
    String: |-
      "(hd0,gpt2)/EFI/centos/bootuuid.cfg\0"
--
    String: |-
      "(hd0,gpt3)/grub2/grub.cfg\0"
--
    String: |-
      "(hd0,gpt3)/grub2/bootuuid.cfg\0"
--
    String: |-
      "(hd0,gpt3)/grub2/grubenv\0"
--
    String: |-
      "(hd0,gpt3)/loader/entries//ostree-1.conf\0"
--
    String: |-
      "(hd0,gpt3)/boot/ostree/default-174d06c7fdfd3ef3dba3c750ed90fb15cadf899db7800bc4330d17e69aaef584/vmlinuz-5.14.0-432.el9.x86_64\0"
--
    String: |-
      "(hd0,gpt3)/boot/ostree/default-174d06c7fdfd3ef3dba3c750ed90fb15cadf899db7800bc4330d17e69aaef584/initramfs-5.14.0-432.el9.x86_64.img\0"
```

I hoped we could extract those files from a bootc container image. When I mounted an image, I couldn't find any files in the boot directory.

By looking at https://github.com/containers/bootc/blob/main/lib/src/bootloader.rs it seems like this is handled by  https://github.com/coreos/bootupd thanks @cgwalters for writing this  https://github.com/containers/bootc/pull/491 in addition.

Where can I find technical details about how does bootupd assemble the boot and EFI partitions? (I'll start by looking a little bit more at the project).

For now... I am creating a small experiment, by converting the container to a qcow2 image, and using guestmount to extract the contents.

**Comment by cgwalters** [comment, marked as answer]
One big help here is that bootupd emphasizes fully static grub config files.  

However, I am sure there are likely to be some things that may need changing here, because e.g.

> "(hd0,gpt3)/loader/entries//ostree-1.conf\0"

That filename is in the general case dynamic, derived from what the boot ordering is.  Very specifically, if one chooses the previous bootloader entry, then this will appear as e.g. ostree-2 and change the measurement.  In some cases that may be desirable, i.e. it's a kind of rollback protection.

> "(hd0,gpt2)/EFI/centos/bootuuid.cfg\0"

Also the *contents* of this one are by default intentionally specific to the installed system, the bootuuid is randomized by default.

> "(hd0,gpt3)/boot/ostree/default-174d06c7fdfd3ef3dba3c750ed90fb15cadf899db7800bc4330d17e69aaef584/vmlinuz-5.14.0-432.el9.x86_64\0"

This checksum includes the kernel/initrd state so we can pre-calculate it, but probably ultimately we should get away from having checksums of things in /boot.

**Reply by mangelajo** [reply]
Ok, so if bootuid is different for each system, we cannot the desired "golden value". And that is ok, may be we should just rely on gathering /sys/kernel/security/tpm0/binary_bios_measurements  + the Quote from the TPM on the final PCR value.

In this way we will have the hashes of each individual file (see a less trimmed version of the bios measurements:
```
  PCRIndex: 9
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "713311575e97fe8dadac271459455ea1a23df5b11189f7ab3c2d836c37dc01ce"
  EventSize: 31
  Event:
    String: |-
      "(hd0,gpt2)/EFI/centos/grub.cfg\0"
...
...
--
  PCRIndex: 9
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "d958607957ab64318a032481f2d3bf8119d151ca3b66fdf2049a13f109f6ce96"
  EventSize: 41
  Event:
    String: |-
      "(hd0,gpt3)/loader/entries//ostree-1.conf\0"
- EventNum: 63
--
  PCRIndex: 9
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "1357cbd9e2a066147493b4ff8b9eb81643f34ecc5475f67cbc3d9a9090e270f9"
  EventSize: 126
  Event:
    String: |-
      "(hd0,gpt3)/boot/ostree/default-174d06c7fdfd3ef3dba3c750ed90fb15cadf899db7800bc4330d17e69aaef584/vmlinuz-5.14.0-432.el9.x86_64\0"
- EventNum: 70
--
  PCRIndex: 9
  EventType: EV_IPL
  DigestCount: 1
  Digests:
  - AlgorithmId: sha256
    Digest: "e4a0ac80a86b828355b04884767ed7cec516ff97b7d4a06b0532333a6b60c1dc"
  EventSize: 132
  Event:
    String: |-
      "(hd0,gpt3)/boot/ostree/default-174d06c7fdfd3ef3dba3c750ed90fb15cadf899db7800bc4330d17e69aaef584/initramfs-5.14.0-432.el9.x86_64.img\0"
- EventNum: 74
```
