### ISSUE TITLE
Stuck on install-to-filesytem

### ISSUE THREAD

**Issue by reavessm** [bootc-dev/bootc#1370]
While following the documentation to [create a libvirt vm image](https://docs.fedoraproject.org/en-US/bootc/qemu-and-libvirt/), The command gets stuck on `Message: Starting module org.osbuild.bootc.install-to-filesystem`.  I also noticed that when I run `iotop -oa`, it shows a kworker thread creating a ton of data...somewhere:

```
Total DISK READ:         0.00 B/s | Total DISK WRITE:        27.80 G/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:       0.00 B/s
    TID  PRIO  USER     DISK READ DISK WRITE>    COMMAND
   2588 be/4 root          0.00 B      6.18 T [kworker/u16:6+loop0]
```

I, in fact, do not have 6+ TB of storage on my laptop.

The worst part about this is the only way to kill this running thread is to hard reboot my laptop (hold the power button down).

Here is the exact command I ran:

```
CONTAINER_IMAGE="quay.io/centos-bootc/centos-bootc:stream9"

podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --rootfs ext4 \
    --local \
    --type qcow2 \
     "${CONTAINER_IMAGE}"
```

I can reproduce this 100% of the time.

Last caveat is that I'm running this on ZFS.  Is this expected?  Is there a way to make this work on ZFS?

**Comment by cgwalters** [comment]
> Last caveat is that I'm running this on ZFS.

This may relate to https://github.com/bootc-dev/bootc/issues/1253

I wonder if there's some pathological I/O patterns here when qcow2 is in use? 

Are you using the zfs storage driver for podman?

**Comment by reavessm** [comment]
> Are you using the zfs storage driver for podman?

Overlayfs

`podman info`:

```
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
```

I haven't used the zfs storage driver since [zfs now supports overlayfs](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0).  And I'm using zfs 2.3.2:

```
> zfs version
zfs-2.3.2-r0-gentoo
zfs-kmod-2.3.2-r0-gentoo
```
